CREATE TABLE CULORI (
    ID_CULOARE NUMBER(10) CONSTRAINT PK_CULORI PRIMARY KEY,
    NUME VARCHAR2(30) CONSTRAINT NN_CULORI_NUME NOT NULL
        CONSTRAINT UNQ_CULORI_NUME UNIQUE
);

CREATE TABLE PRODUSE (
    ID_PRODUS NUMBER(10) CONSTRAINT PK_PRODUSE PRIMARY KEY,
    CULOARE_ID NUMBER(10),
    NUME VARCHAR2(30) CONSTRAINT NN_PRODUSE_NUME NOT NULL,
    PRET NUMBER(7, 2) CONSTRAINT NN_PRODUSE_PRET NOT NULL
                      CONSTRAINT CHK_PRODUSE_PRET CHECK (PRET > 0),
    DESCRIERE VARCHAR2(3000) CONSTRAINT NN_PRODUSE_DESCRIERE NOT NULL,
    CONSTRAINT FK_PRODUSE_CULOARE_ID FOREIGN KEY (CULOARE_ID) REFERENCES CULORI (ID_CULOARE)
);

CREATE TABLE CATEGORII (
    ID_CATEGORIE NUMBER(10) CONSTRAINT PK_CATEGORII PRIMARY KEY,
    NUME VARCHAR2(50) CONSTRAINT NN_CATEGORII_NUME NOT NULL CONSTRAINT UNQ_CATEGORII_NUME UNIQUE,
    ESTE_FAMILIE NUMBER(1) CONSTRAINT CHK_CATEGORII_ESTE_FAMILIE CHECK (ESTE_FAMILIE IS NOT NULL AND ESTE_FAMILIE = 0 OR ESTE_FAMILIE = 1)
);

CREATE TABLE LK_CATEGORII_PRODUSE (
    PRODUS_ID NUMBER(10),
    CATEGORIE_ID NUMBER(10),
    CONSTRAINT PK_CATEGORII_PRODUSE PRIMARY KEY (CATEGORIE_ID, PRODUS_ID),
    CONSTRAINT FK_CATPROD_CATEGORIE_ID FOREIGN KEY (CATEGORIE_ID) REFERENCES CATEGORII(ID_CATEGORIE),
    CONSTRAINT FK_CATPROD_PRODUS_ID FOREIGN KEY (PRODUS_ID) REFERENCES PRODUSE (ID_PRODUS)
);

CREATE TABLE ORASE (
    ID_ORAS NUMBER(10) CONSTRAINT PK_ORASE_ID_ORAS PRIMARY KEY,
    NUME VARCHAR2(30)
);

CREATE TABLE UTILIZATORI (
    ID_UTILIZATOR NUMBER(10) CONSTRAINT PK_UTILIZATORI PRIMARY KEY,
    ORAS_ID NUMBER(10),
    NUME VARCHAR2(30) CONSTRAINT NN_UTILIZATORI_NUME NOT NULL,
    PRENUME VARCHAR2(30) CONSTRAINT NN_UTILIZATORI_PRENUME NOT NULL,
    ADRESA VARCHAR2(150) CONSTRAINT NN_UTILIZATORI_ADRESA NOT NULL,
    CONSTRAINT FK_UTILIZATORI_ORAS_ID FOREIGN KEY (ORAS_ID) REFERENCES ORASE (ID_ORAS)
);

CREATE TABLE DESTINATII_RIDICARE (
    ID_DESTINATIE NUMBER(10) CONSTRAINT PK_DESTINATII_RIDICARE_ID_DESTINATIE PRIMARY KEY,
    ORAS_ID NUMBER(10) CONSTRAINT NN_DESTINATII_RIDICARE_ORAS_ID NOT NULL,
    NUME VARCHAR2(50) CONSTRAINT UNQ_DESTINATII_RIDICARE_NUME UNIQUE CONSTRAINT NN_DESTINATII_RIDICARE_NUME NOT NULL,
    ADRESA VARCHAR2(200) CONSTRAINT NN_DESTINATII_RIDICARE_ADRESA NOT NULL,
    DESCRIERE VARCHAR2(500),
    CONSTRAINT FK_DESTINATII_RIDICARE_ORAS_ID FOREIGN KEY (ORAS_ID) REFERENCES ORASE (ID_ORAS)
);

CREATE TABLE COMENZI (
    ID_COMANDA NUMBER(10) CONSTRAINT PK_COMENZI PRIMARY KEY,
    FINALIZATA NUMBER(1) CONSTRAINT NN_COMENZI_FINALIZATA NOT NULL,
    DESTINATIE_ID NUMBER(10),
    TIP_DESTINATIE VARCHAR2(10) CONSTRAINT CHK_COMENZI_TIP_DESTINATIE CHECK (TIP_DESTINATIE IN ('MAGAZIN', 'PUNCT', 'DOMICILIU')),
    DATA DATE CONSTRAINT NN_COMENZI_DATA NOT NULL,
    CONSTRAINT FK_COMENZI_DESTINATIE_ID FOREIGN KEY (DESTINATIE_ID) REFERENCES DESTINATII_RIDICARE (ID_DESTINATIE)
);

CREATE TABLE LK_UTILIZATORI_COMENZI_PRODUSE (
    UTILIZATOR_ID NUMBER(10),
    COMANDA_ID NUMBER(10),
    PRODUS_ID NUMBER(10),
    CANTITATE NUMBER(3) CONSTRAINT NN_UCP_CANTITATE NOT NULL
                        CONSTRAINT CHK_UCP_CANTITATE CHECK (CANTITATE > 0),
    CONSTRAINT PK_UTILIZATORI_COMENZI_PRODUSE PRIMARY KEY (UTILIZATOR_ID, COMANDA_ID, PRODUS_ID),
    CONSTRAINT FK_UCP_UTILIZATOR_ID FOREIGN KEY (UTILIZATOR_ID) REFERENCES UTILIZATORI(ID_UTILIZATOR),
    CONSTRAINT FK_UCP_COMANDA_ID FOREIGN KEY (COMANDA_ID) REFERENCES COMENZI(ID_COMANDA),
    CONSTRAINT FK_UCP_PRODUS_ID FOREIGN KEY (PRODUS_ID) REFERENCES PRODUSE(ID_PRODUS)
);